"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-08
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_salt", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,  # never hand a deleted user's id to someone new
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "budgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("limit_paise", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "category", name="uq_budget_category"),
    )
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_budgets_user_id"), ["user_id"], unique=False)

    op.create_table(
        "imports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("added", sa.Integer(), nullable=False),
        sa.Column("duplicates", sa.Integer(), nullable=False),
        sa.Column("skipped", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("imports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_imports_user_id"), ["user_id"], unique=False)

    op.create_table(
        "import_duplicates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("import_id", sa.Integer(), nullable=False),
        sa.Column("dedup_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.ForeignKeyConstraint(["import_id"], ["imports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_duplicates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_import_duplicates_dedup_key"), ["dedup_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_import_duplicates_import_id"), ["import_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_import_duplicates_user_id"), ["user_id"], unique=False)

    op.create_table(
        "merchant_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("merchant_key", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "merchant_key", name="uq_merchant_category"),
    )
    with op.batch_alter_table("merchant_categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_merchant_categories_user_id"), ["user_id"], unique=False)

    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("merchant", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
        sa.Column("amount_paise", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("category_source", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("import_id", sa.Integer(), nullable=True),
        sa.Column("dedup_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["import_id"], ["imports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dedup_key", name="uq_transaction_dedup"),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_transactions_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_transactions_import_id"), ["import_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_transactions_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_transactions_user_date", ["user_id", "date"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_transactions_user_date")
        batch_op.drop_index(batch_op.f("ix_transactions_user_id"))
        batch_op.drop_index(batch_op.f("ix_transactions_import_id"))
        batch_op.drop_index(batch_op.f("ix_transactions_date"))

    op.drop_table("transactions")
    with op.batch_alter_table("merchant_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_merchant_categories_user_id"))

    op.drop_table("merchant_categories")
    with op.batch_alter_table("import_duplicates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_duplicates_user_id"))
        batch_op.drop_index(batch_op.f("ix_import_duplicates_import_id"))
        batch_op.drop_index(batch_op.f("ix_import_duplicates_dedup_key"))

    op.drop_table("import_duplicates")
    with op.batch_alter_table("imports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_imports_user_id"))

    op.drop_table("imports")
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budgets_user_id"))

    op.drop_table("budgets")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
